version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      DATABASE_URL: postgres://user:password@database:5432/documents
    networks:
      - app-network

  rag-api:
    build: ./rag-service
    ports:
      - "8001:8001"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: documents
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
